package:
  name: sowhat
  version: 0.9.0

source:
  git_rev: 0.9.0
  git_url: https://github.com/josephryan/sowhat.git

requirements:
  build:
    - perl-ipc-run

  run:
    - seq-gen
    - raxml
    - perl-statistics-r

test:
  imports:
    - raxml -v
    - seq-gen -h

about:
  home: https://github.com/josephryan/sowhat
  license: GPLv3.0
  license_file: LICENSE

