package:
  name: sowhat
  version: 0.9.0

source:
  git_branch: Development
  git_url: https://github.com/josephryan/sowhat.git

build:
  number: 0
  rpaths:
    - lib/
    - lib/R/lib/

requirements:
  build:
    - perl # [not osx]
    - perl-app-cpanminus
    - seq-gen
    - raxml
    - r-base
    - r-ape

  run:
    - perl # [not osx]
    - perl-app-cpanminus
    - seq-gen
    - raxml
    - r-base
    - r-ape

about:
  home: https://github.com/josephryan/sowhat
  license: GPLv3.0
  license_file: LICENSE

